version: '3'

services:
  web:
    container_name: "django_tutorial_web"
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - ./app:/code
    depends_on:
      - db
  db:
    container_name: "django_tutorial_db"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "django_tutorial_db"
      MYSQL_USER: django_tutorialuser
      MYSQL_PASSWORD: django_tutorialpass
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
